import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.sql.Time;
import java.util.Date;
import java.util.List;

public class CreatePromotion {
    public static void main(String[] args) throws InterruptedException {
        System.setProperty("WebDriver.chrome.driver", "/Users/sankalppatil/Documents/Chrome_Driver/chromedriver");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://twostaging.carrot.club");
        Thread.sleep(1000);
        driver.findElement(By.xpath("//div[8]//div[1]//div[1]//div[2]")).click();
        driver.findElement(By.id("mui-1")).sendKeys("krishna@carrot.club");
        driver.findElement(By.id("mui-2")).sendKeys("12341234");
        driver.findElement(By.tagName("button")).click();
        Thread.sleep(1000);
        driver.navigate().refresh();
        driver.navigate().refresh();
        driver.navigate().to("https://twostaging.carrot.club/promotion");
        Thread.sleep(1000);
        WebElement Promobutton = driver.findElement(By.cssSelector(".MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeMedium.MuiButton-containedSizeMedium.css-1jce7q"));
        Promobutton.click();
        Thread.sleep(2000);
        driver.findElement(By.name("promoName")).sendKeys("RafiquePromo");
        Thread.sleep(1000);
        WebElement Date = driver.findElement(By.xpath("(//label[normalize-space()='Start Date & Time'])[1]"));
        Date.click();
        String targetDate = "24";
        WebElement targetDateElement = driver.findElement(By.xpath("(//button[normalize-space()="+targetDate+"])[1]"));
        targetDateElement.click();
        Thread.sleep(1000);
       WebElement ok = driver.findElement(By.xpath("(//button[normalize-space()='OK'])[1]"));
       ok.click();
       ok.sendKeys(Keys.TAB);
        //String targetTime = "12.34 PM";
        //Time.sendKeys(targetTime);
       Thread.sleep(1000);
        WebElement Date2 = driver.findElement(By.xpath("/html[1]/body[1]/div[2]/div[3]/div[2]/div[1]/div[2]/div[1]/p[1]/form[1]/div[1]/div[4]/div[1]/div[1]/input[1]"));
       Date2.click();
        //String endDate = "30";
       Thread.sleep(1000);
        WebElement button = driver.findElement(By.xpath("(//button[normalize-space()='30'])[1]"));
        button.click();
        Thread.sleep(1000);
        driver.findElement(By.xpath("/html[1]/body[1]/div[3]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[2]/span[1]")).click();
        driver.findElement(By.xpath("/html[1]/body[1]/div[3]/div[3]/div[1]/div[1]/div[1]/div[3]/button[2]")).click();
        Thread.sleep(1000);
        driver.findElement(By.name("badgeText")).sendKeys("Selenium Promo");
        Thread.sleep(1000);
        driver.findElement(By.name("promoDesc")).sendKeys("Selenium Promo");
        Thread.sleep(1000);
        driver.findElement(By.xpath("(//div[@class='ql-editor ql-blank'])[1]")).sendKeys("Selenium Promo T&C");
        driver.findElement(By.xpath("//button[normalize-space()='Next']")).click();
        //driver.navigate().refresh();
        Thread.sleep(2000);
        WebElement Dropdown=driver.findElement(By.xpath("(//div[contains(@role,'button')])[2]"));
        Dropdown.click();
        Thread.sleep(1000);
        WebElement DropdownSelection = driver.findElement(By.xpath("(//li[@role='option'])[2]"));
        DropdownSelection.click();
        DropdownSelection.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("/html[1]/body[1]/div[2]/div[3]/div[2]/div[1]/div[3]/div[1]/p[1]/form[1]/div[1]/div[2]/div[1]/div[1]")).click();
        WebElement ChannelType = driver.findElement(By.xpath("(//li[@role='option'])[2]"));
        ChannelType.click();
        ChannelType.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("/html[1]/body[1]/div[2]/div[3]/div[2]/div[1]/div[3]/div[1]/p[1]/form[1]/div[1]/div[3]/div[1]/div[1]")).click();
        WebElement Category = driver.findElement(By.xpath("(//li[@role='option'])[1]"));
        Category.click();
        Category.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("(//button[@type='submit'])[2]")).click();
    }
}